# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(default='', max_length=255, unique=True, verbose_name='document key')),
                ('description', models.CharField(default='', max_length=4096, verbose_name='description')),
                ('short_description', models.CharField(default='', max_length=255, verbose_name='short description')),
            ],
            options={
                'verbose_name_plural': 'agreements',
                'verbose_name': 'agreement',
            },
        ),
        migrations.CreateModel(
            name='AgreementUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateTimeField(auto_now_add=True, verbose_name='acceptance date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
            ],
            options={
                'verbose_name_plural': 'agreement users',
                'verbose_name': 'agreement user',
            },
        ),
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(default='', max_length=255, verbose_name='short title')),
                ('full_title', models.CharField(default='', max_length=1023, verbose_name='full title')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('content_format', models.CharField(choices=[('TEXT', 'Plain Text'), ('HTML', 'HTML'), ('MARK', 'Markdown'), ('REST', 'ReStructured Text')], default='TEXT', max_length=8, verbose_name='content format')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='release date')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assent.Agreement', verbose_name='agreement')),
                ('users', models.ManyToManyField(related_name='agreement_versions', through='assent.AgreementUser', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name_plural': 'agreement versions',
                'get_latest_by': ('release_date',),
                'ordering': ('-release_date',),
                'verbose_name': 'agreement version',
            },
        ),
        migrations.AddField(
            model_name='agreementuser',
            name='agreement_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_users', to='assent.AgreementVersion', verbose_name='agreement_version'),
        ),
        migrations.AddField(
            model_name='agreementuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
