# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(default='', max_length=255, unique=True, verbose_name='document key')),
                ('slug', models.SlugField(default='', max_length=255, verbose_name='slug')),
                ('description', models.CharField(default='', max_length=4096, verbose_name='description')),
                ('short_description', models.CharField(default='', max_length=255, verbose_name='short description')),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'agreement',
                'verbose_name_plural': 'agreements',
            },
        ),
        migrations.CreateModel(
            name='AgreementUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateTimeField(blank=True, null=True, verbose_name='acceptance date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'agreement user',
                'verbose_name_plural': 'agreement users',
            },
        ),
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(default='', max_length=255, verbose_name='short title')),
                ('full_title', models.CharField(default='', max_length=1023, verbose_name='full title')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('content_format', models.CharField(default='', max_length=4, verbose_name='Content format')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='release date')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assent.Agreement', verbose_name='agreement')),
                ('users', models.ManyToManyField(related_name='agreement_versions', through='assent.AgreementUser', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'agreement version',
                'get_latest_by': ('release_date',),
                'verbose_name_plural': 'agreement versions',
                'ordering': ('-release_date',),
            },
        ),
        migrations.AddField(
            model_name='agreementuser',
            name='agreement_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_users', to='assent.AgreementVersion', verbose_name='agreement_version'),
        ),
        migrations.AddField(
            model_name='agreementuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='latest_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_latest_version', to='assent.AgreementVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='agreementuser',
            unique_together=set([('user', 'agreement_version')]),
        ),
    ]
